name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: 4d352eb7d5eaecee08be13de33c185bc9aeabcfb
        with:
          args: >
            -Dsonar.projectKey=shalykerk_NodeGoat-a2
            -Dsonar.organization=shalykerk
            -Dsonar.sources=.
